[1.0.0.1] Add initial helm resources for Choreo Connect Deployment
wso2/kubernetes-microgateway pull request #23
Opened 2022-01-20 07:59 UTC by renuka-fernando

## Purpose
Resolves https://github.com/wso2/kubernetes-microgateway/issues/22
$subject

2022-01-21 14:21 UTC, chirangaalwis requested changes

2022-01-21 14:21 UTC, chirangaalwis commented on helm/choreo-connect/README.md
> + helm install --name <RELEASE_NAME> <HELM_HOME>/choreo-connect --version 1.0.0-1 --namespace <NAMESPACE>
```suggestion
 helm install --name <RELEASE_NAME> <HELM_HOME>/choreo-connect --namespace <NAMESPACE>
```

2022-01-21 14:21 UTC, chirangaalwis commented on helm/choreo-connect/README.md
> +helm install <RELEASE_NAME> <HELM_HOME>/choreo-connect --version 1.0.0-1 --namespace <NAMESPACE> --create-namespace
```suggestion
helm install <RELEASE_NAME> <HELM_HOME>/choreo-connect --namespace <NAMESPACE> --create-namespace
```

2022-01-21 14:21 UTC, chirangaalwis commented on helm/choreo-connect/README.md
> + helm install --name <RELEASE_NAME> <HELM_HOME>/choreo-connect --version 1.0.0-1 --namespace <NAMESPACE> --set wso2.subscription.username=<SUBSCRIPTION_USERNAME> --set wso2.subscription.password=<SUB
```suggestion
 helm install --name <RELEASE_NAME> <HELM_HOME>/choreo-connect --namespace <NAMESPACE> --set wso2.subscription.username=<SUBSCRIPTION_USERNAME> --set wso2.subscription.password=<SUBSCRIPTION_PASSWORD>
```

2022-01-21 14:21 UTC, chirangaalwis commented on helm/choreo-connect/auth.json
> +}
@renuka-fernando please add a new EOF line.

2022-01-21 14:26 UTC, chirangaalwis requested changes

2022-01-21 14:26 UTC, chirangaalwis commented on helm/choreo-connect/templates/enforcer-grpc-probe-script-configmap.yaml
> +        -connect-timeout=3s
@renuka-fernando please add a new EOF line.

2022-01-21 14:41 UTC, pubudu538 approved these changes

2022-01-24 05:50 UTC, chirangaalwis requested changes

2022-01-24 05:50 UTC, chirangaalwis commented on CHANGELOG.md
> +## [v1.0.0.1] - 2022-01-21
```suggestion
## [v1.0.0.1] - 2022-01-24
```

2022-01-24 06:08 UTC, chirangaalwis approved these changes

2022-01-24 06:12 UTC, merged